const steps = [
  "IDENTIFICATION OF CYLINDER",
  "RECORD OF THE IDENTITY - DEGASSING PROCESS",
  "EXTERNAL VISUAL INSPECTION",
  "INTERNAL WASHING",
  "INTERNAL VISUAL INSPECTION",
  "TARE WEIGHT",
  "INSPECTION OF CYLINDER NECK",
  "ULTRASONIC THICKNESS MEASUREMENT",
  "HYDRAULIC VOLUMETRIC EXPANSION",
  "CYLINDER DRYING PROCESS",
  "ULTRASONIC FLAW DETECTION TESTING",
  "PAINTING",
  "TARE WEIGHT",
  "RE-VALVING OF CYLINDER",
  "RE-TEST MARKING",
  "DISPATCH WITH CERTIFICATE",
];

export default steps;
